<?xml version="1.0"?>
<package format="2">
    <name>network_communication</name>
    <version>2.0.0</version>
    <description>Library providing network functionality for sending ROS data via UDP</description>
    <maintainer email="simon_sagmeister@tum.de">Simon Sagmeister</maintainer>
    <license>Apache 2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    <depend>ament_index_cpp</depend>
    <depend>rclcpp</depend>
    <depend>nav_msgs</depend>
    <depend>tum_msgs</depend>
    <depend>tum_ros_helpers_cpp</depend>
  
    <test_depend>ament_cmake_gtest</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
